# Generated by Django 4.2.7 on 2025-05-13 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonneesBiometriques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripteur_facial', models.BinaryField(blank=True, null=True)),
                ('date_capture', models.DateTimeField(auto_now_add=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometrie', to='etudiants.etudiant')),
            ],
            options={
                'verbose_name': 'Données biométriques',
                'verbose_name_plural': 'Données biométriques',
            },
        ),
    ]
