# Generated by Django 4.2.7 on 2025-05-13 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presences', '0002_messagetemplate_message_contenu_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='contenu_html',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_lecture',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_programmee',
        ),
        migrations.RemoveField(
            model_name='message',
            name='est_lu',
        ),
        migrations.RemoveField(
            model_name='message',
            name='template',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tracking_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echec', 'Échec')], default='en_attente', max_length=10),
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
    ]
